use GEDMAF;
select COLUMN_NAME, DATA_TYPE, CHARACTER_OCTET_LENGTH
from INFORMATION_SCHEMA.COLUMNS c
where TABLE_SCHEMA = 'Ref'
and TABLE_CATALOG = 'GEDMAF'
and TABLE_NAME = 'TypeDocument'
order by COLUMN_NAME