USE [GEDMAF]
GO

select C.COLUMN_NAME, C.DATA_TYPE, C.CHARACTER_OCTET_LENGTH
from INFORMATION_SCHEMA.COLUMNS C
WHERE C.TABLE_SCHEMA = 'GED'
AND C.TABLE_CATALOG = 'GEDMAF'
AND C.TABLE_NAME = 'NormalizedDocument'
ORDER BY C.COLUMN_NAME